name: weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: any
  equatable: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^5.0.0
  http: ^0.12.0
  intl: any
  mockito: ^5.0.16
  rxdart: ^0.25.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
